<?php
/*
 * Created on Jul 27, 2008 by Jason Grosman
 * This work is licensed under the Creative Commons Attribution-Noncommercial 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc/3.0/ or send a letter to Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
 *
 */

// Add your NPR API key here
// Go to http://www.npr.org/api to register for one
$apiKey = 'API KEY HERE';
$resultsPerPage = 10;
?>